### ISSUE TITLE
pytest macros missing export on PYTHONPATH?

### ISSUE THREAD

**Issue by sebix** [openSUSE/python-rpm-macros#43] opened 2020-05-16 18:58 UTC
I just tried to use the `%pytest_arch` macro for the python-typed-ast package, but it failed with 
```
[   37s] + PYTHONPATH=:/home/abuild/rpmbuild/BUILDROOT/python-typed-ast-1.4.1-0.x86_64/usr/lib64/python3.8/site-packages
[   37s] + PYTHONDONTWRITEBYTECODE=1
[   37s] + py.test-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v
[   37s] ============================= test session starts ==============================
[   37s] platform linux -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
[   37s] cachedir: .pytest_cache
[   37s] rootdir: /home/abuild/rpmbuild/BUILD/typed_ast-1.4.1
[   38s] collecting ... collected 0 items / 1 error
[   38s] 
[   38s] ==================================== ERRORS ====================================
[   38s] __________________ ERROR collecting ast3/tests/test_basics.py __________________
[   38s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/typed_ast-1.4.1/ast3/tests/test_basics.py'.
[   38s] Hint: make sure your test modules/packages have valid Python names.
[   38s] Traceback:
[   38s] ast3/tests/test_basics.py:5: in <module>
[   38s]     from typed_ast import _ast3
[   38s] E   ImportError: cannot import name '_ast3' from 'typed_ast' (/home/abuild/rpmbuild/BUILD/typed_ast-1.4.1/typed_ast/__init__.py)
[   38s] !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[   38s] =============================== 1 error in 0.10s ===============================
```
However, executing the same commands with `export PYTHONPATH=...` works fine. Is this only a problem in this package or maybe in general?

**Comment by scarabeusiv** [comment] 2020-05-18 06:30
The problem is not in the macro. The macro imports also prefer the local folder, so it tries to import the generated .so from the $(pwd) first, where it ain't present and fails over.

**Comment by bnavigator** [comment] 2020-06-22 13:44
Realted to #31, which is closed by 503823c8c45843a2f8787956ec160671b7d58b75

So it WAS the macro. It introduced the empty dir in PYTHONPATH.

**Comment by mcepl** [comment] 2020-06-23 15:18
Duplicate of #31, then?

**Closed by mcepl** 2020-06-23 15:18 UTC

**Comment by sebix** [comment] 2020-06-25 07:18
Thanks!
