### ISSUE TITLE
make python-rpm-macros more common

### ISSUE THREAD

**Issue by huakim** [openSUSE/python-rpm-macros#183] opened 2024-10-02 11:31 UTC
I wish to create project like lua-rpm-macros for same purpose as python-rpm-macros, but for lua programming language. This project already created, but buggy and depends on python311-specfile. It seems, that python-rpm-macros project have a lot of  functions, than  can be used on lua-rpm-macros project. Maybe, python-rpm-macros should be splitted to python-rpm-macros and rpm-macros-common? Also, all the functions can be placed into file, which can be located at directory  /usr/lib/rpm/lua/, instead of compiling all of them
In lua variant of python-rpm-macros, we can define an flavors lua51, lua53, lua54, luajit, rpmlua
The lua2pack, variant of py2pack, is exists and working well

**Comment by mcepl** [comment] 2024-10-03 13:46
Are we talking about https://github.com/huakim/lua-rpm-macros ? That's 30k uncompressed. Do we really need some architecture for it, or are we in the realms of [astro design](https://www.joelonsoftware.com/2001/04/21/dont-let-architecture-astronauts-scare-you/)?

Rewriting `specfile` Python plugin to Lua could be more interesting than that.

**Comment by bnavigator** [comment] 2024-10-04 11:05
I don't think it is prudent to try to make the already loaded and crufty python-rpm-macros more general. Look at `python_subpackages()`.

 https://github.com/openSUSE/python-rpm-macros/blob/c146b29d5b88a2d8e3e94a6454abb97cd6643237/macros.lua#L59-L413

 It is almost 400 lines long and barely anybody dares to touch it. When I tried to make it fit for parallel python3 multiflavors, I even had problems to explain the stuff to the reviewers.

Unless we are completely rewriting the macros with modern and clear design principles, python-rpm-macros is stuck in maintenance with minimum enhancements.

**Comment by huakim** [comment] 2024-10-22 08:45
Maybe, we should patch rpm-build package, to order to add ability to write somewhere information about parse result from spec file before %build process, and write %python_generate_subpackage_specparts, which will run during %build to order to generate necessary specparts?

**Comment by mcepl** [comment] 2024-12-17 19:56
The same problem as #189: a lot of talk without actionable items. Show me the code!

And anyway, this is just a duplicate of #189.

**Closed by mcepl** 2024-12-17 19:56 UTC
